Repository VirtualZeth/new-yorker.dk, pull requests merged in 2021-06, with the labels that each got.

#48 Add Mission_og_Vision_Virksomhedsafsnit.md
  09 Report/Anders (VirtualZeth)/Mission_og_Vision_Virksomhedsafsnit.md
Labels: report

#49 Create Teknologi-Android.md
  09 Report/Danijel/Teknologi-Android.md
Labels: report

#74 Fix leaky context using WeakReference
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/entities/ContactForm.java
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/usecase/JavaMailAPI.java
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/usecase/MailService.java
Labels: bug

#75 Android splash screen
  08 implementation/Mobile App/.idea/misc.xml
  08 implementation/Mobile App/app/src/main/AndroidManifest.xml
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/UI/BasketFragment.java
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/UI/SplashScreenActivity.java
  08 implementation/Mobile App/app/src/main/res/drawable/newyork_logo.webp
  08 implementation/Mobile App/app/src/main/res/drawable/yorknew.xml
  08 implementation/Mobile App/app/src/main/res/layout/activity_fragment_splash_screen.xml
  08 implementation/Mobile App/app/src/main/res/layout/fragment_basket.xml
  08 implementation/Mobile App/app/src/main/res/values/themes.xml
  08 implementation/Mobile App/build.gradle
Labels: feature

#80 implement contact us webview,
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/UI/fragments/MainFragment.java
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/UI/fragments/PriceExamplesFragment.java
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/UI/fragments/WebViewFragment.java
  08 implementation/Mobile App/app/src/main/res/layout/fragment_webview.xml
Labels: feature

#82 Android basket feature
  .idea/runConfigurations.xml
  08 implementation/Mobile App/.gitignore
  08 implementation/Mobile App/app/build.gradle
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/UI/fragments/BasketFragment.java
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/UI/fragments/RecyclerViewAdapter.java
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/entities/Wall.java
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/viewmodels/SharedViewModel.java
  08 implementation/Mobile App/app/src/main/res/drawable/horizontal_divider.xml
  08 implementation/Mobile App/app/src/main/res/layout/fragment_basket.xml
  08 implementation/Mobile App/app/src/main/res/layout/item.xml
  08 implementation/Mobile App/app/src/main/res/values/strings.xml
Labels: feature

#84 Initial Front Page Design
  08 implementation/Mobile App/app/src/main/res/drawable/frontpage_bg.jpg
  08 implementation/Mobile App/app/src/main/res/font/open_sans_regular.ttf
  08 implementation/Mobile App/app/src/main/res/layout/fragment_main.xml
  08 implementation/Mobile App/app/src/main/res/values/colors.xml
  08 implementation/crud-app/.gitignore
  08 implementation/crud-app/README.md
  08 implementation/crud-app/package-lock.json
  08 implementation/crud-app/package.json
  08 implementation/crud-app/public/favicon.ico
  08 implementation/crud-app/public/index.html
  08 implementation/crud-app/public/logo192.png
  08 implementation/crud-app/public/logo512.png
  08 implementation/crud-app/public/manifest.json
  08 implementation/crud-app/public/robots.txt
  08 implementation/crud-app/src/App.js
  08 implementation/crud-app/src/actions/auth.js
  08 implementation/crud-app/src/actions/category.js
  08 implementation/crud-app/src/actions/modals.js
  08 implementation/crud-app/src/actions/types.js
  08 implementation/crud-app/src/components/AddProductModal.js
  08 implementation/crud-app/src/components/CategoryModal.js
  08 implementation/crud-app/src/components/Table.js
  08 implementation/crud-app/src/components/Toolbar.js
  08 implementation/crud-app/src/components/views/Dashboard.js
  08 implementation/crud-app/src/components/views/Login.js
  08 implementation/crud-app/src/firebase.js
  08 implementation/crud-app/src/index.js
  08 implementation/crud-app/src/reducers/auth.js
  08 implementation/crud-app/src/reducers/category.js
  08 implementation/crud-app/src/reducers/index.js
  08 implementation/crud-app/src/reducers/modals.js
  08 implementation/crud-app/src/store.js
  08 implementation/crud-app/src/styling/App.css
Labels: design

#85 CRUD App First edition
  08 implementation/crud-app/src/components/CategoryModal.js
  08 implementation/crud-app/src/components/Toolbar.js
Labels: feature

#87 Implement delete on click recycler
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/UI/fragments/BasketFragment.java
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/UI/fragments/RecyclerViewAdapter.java
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/usecase/sendrequest/JavaMailAPI.java
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/usecase/sendrequest/MailCredentials.java
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/usecase/sendrequest/MailService.java
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/viewmodels/SharedViewModel.java
  08 implementation/Mobile App/app/src/main/res/layout/fragment_basket.xml
  08 implementation/Mobile App/app/src/main/res/layout/item.xml
  08 implementation/Mobile App/app/src/main/res/values/strings.xml
Labels: feature

#63 Create Finansering.md
  09 Report/Danijel/Finansering.md
Labels: report

#96 Add files via upload
  01 Business Modeling/Domænemodel.vsdx
Labels: documentation

#95 Create Klassediagram
  02 Requirements/Klassediagram/Klassediagram.png
  02 Requirements/Klassediagram/Klassediagram.vsdx
Labels: documentation

#94 Add operation contracts
  02 Requirements/Operationscontracts/Angiv_Besked.md
  02 Requirements/Operationscontracts/Angiv_By.md
  02 Requirements/Operationscontracts/Angiv_Forhandler.md
  02 Requirements/Operationscontracts/Angiv_Telefonnummer.md
  02 Requirements/Operationscontracts/OC_Angiv_Bredde.md
  02 Requirements/Operationscontracts/OC_Angiv_Email.md
  02 Requirements/Operationscontracts/OC_Angiv_Felter_På_Langs.md
  02 Requirements/Operationscontracts/OC_Angiv_Felter_På_Tvaers.md
  02 Requirements/Operationscontracts/OC_Angiv_Højde.md
  02 Requirements/Operationscontracts/OC_Angiv_Navn.md
  02 Requirements/Operationscontracts/OC_Angiv_Note_Til_Væg.md
  02 Requirements/Operationscontracts/OC_Fortsæt_Til_Kontaktformular.md
  02 Requirements/Operationscontracts/OC_Gem_Ændring.md
  02 Requirements/Operationscontracts/OC_Rediger_Væg.md
  02 Requirements/Operationscontracts/OC_Send_Forespørgsel.md
  02 Requirements/Operationscontracts/OC_Slet_Væg.md
  02 Requirements/Operationscontracts/OC_Tilføj_Til_Kurv.md
  02 Requirements/Operationscontracts/OC_Vis_Kurv.md
  02 Requirements/Operationscontracts/OC_Vælg_Tillæg.md
Labels: documentation

#89 Tilføj SSD bestil væg
  02 Requirements/SSD_Bestil_Væg.vsdx
Labels: documentation

#99 Tilføj SD Bestil væg
  02 Requirements/sekvensdiagrammer/SDBestilVæg.vsdx
Labels: documentation

#107 Implementer CRUD fejlhåndtering
  08 implementation/crud-app/package-lock.json
  08 implementation/crud-app/package.json
  08 implementation/crud-app/src/App.js
  08 implementation/crud-app/src/actions/alerts.js
  08 implementation/crud-app/src/actions/modals.js
  08 implementation/crud-app/src/actions/types.js
  08 implementation/crud-app/src/components/Alert.js
  08 implementation/crud-app/src/components/Table.js
  08 implementation/crud-app/src/components/Toolbar.js
  08 implementation/crud-app/src/components/modals/AddProductModal.js
  08 implementation/crud-app/src/components/modals/CategoryModal.js
  08 implementation/crud-app/src/components/modals/DeleteModal.js
  08 implementation/crud-app/src/components/views/Login.js
  08 implementation/crud-app/src/reducers/alerts.js
  08 implementation/crud-app/src/reducers/auth.js
  08 implementation/crud-app/src/reducers/category.js
  08 implementation/crud-app/src/reducers/index.js
  08 implementation/crud-app/src/reducers/modals.js
Labels: feature

#109 Tilføjet slet alt feature
  08 implementation/Mobile App/.idea/compiler.xml
  08 implementation/Mobile App/app/build.gradle
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/UI/activities/SplashScreenActivity.java
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/UI/fragments/BasketFragment.java
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/viewmodels/SharedViewModel.java
  08 implementation/Mobile App/app/src/main/res/layout/fragment_basket.xml
  08 implementation/Mobile App/app/src/main/res/values/strings.xml
Labels: feature

#113 Redigeret i designet
  08 implementation/Mobile App/app/src/main/res/layout/fragment_basket.xml
Labels: design

#114 Override onstop
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/UI/fragments/BasketFragment.java
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/UI/fragments/BuildWallFragment.java
Labels: bug

#115 Add new current wall when "Tilføj" is clicked,
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/UI/adapters/RecyclerViewAdapter.java
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/UI/fragments/BuildWallFragment.java
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/usecase/sendrequest/MailCredentials.java
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/usecase/sendrequest/MailService.java
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/viewmodels/SharedViewModel.java
Labels: bug

#50 Create Forretningsmodel.md
  09 Report/Danijel/Forretningsmodel.md
Labels: report

#116 Override onstop, implement backbutton
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/UI/activities/MainActivity.java
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/UI/fragments/BasketFragment.java
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/UI/fragments/BuildWallFragment.java
Labels: bug

#119 Implement addition toggle, no checkmarks yet
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/entities/Wall.java
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/viewmodels/SharedViewModel.java
Labels: feature

#120 Correct the method call to toggleAddition
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/UI/fragments/BuildWallFragment.java
Labels: bug

#123 implement automatic width and height suggestion for amount of fields
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/UI/fragments/BuildWallFragment.java
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/entities/Wall.java
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/viewmodels/SharedViewModel.java
Labels: feature

#124 Fix error introduced by previous merg
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/entities/Wall.java
Labels: bug

#125 Android change UI
  08 implementation/Mobile App/app/src/main/res/layout/fragment_basket.xml
  08 implementation/Mobile App/app/src/main/res/layout/fragment_build_wall.xml
Labels: bug

#130 Android UI fix text wall
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/UI/activities/MainActivity.java
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/UI/activities/SplashScreenActivity.java
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/UI/adapters/AdditionsExpandableListAdapter.java
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/UI/adapters/RecyclerViewAdapter.java
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/UI/fragments/BasketFragment.java
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/UI/fragments/BuildWallFragment.java
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/UI/fragments/ContactUsFragment.java
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/UI/fragments/MainFragment.java
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/UI/fragments/WebViewFragment.java
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/UI/util/MinMaxInputFilter.java
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/data/FireStoreDB.java
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/entities/Addition.java
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/entities/Basket.java
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/entities/Wall.java
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/usecase/sendrequest/JavaMailAPI.java
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/usecase/sendrequest/MailCredentials.java
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/usecase/sendrequest/MailService.java
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/usecase/sendrequest/PriceEstimator.java
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/viewmodels/SharedViewModel.java
  08 implementation/Mobile App/app/src/main/res/layout/fragment_build_wall.xml
  08 implementation/Mobile App/app/src/main/res/values/strings.xml
Labels: bug

#132 Android reformat again
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/UI/adapters/RecyclerViewAdapter.java
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/UI/fragments/BuildWallFragment.java
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/entities/Addition.java
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/entities/Wall.java
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/usecase/sendrequest/PriceEstimator.java
  08 implementation/Mobile App/app/src/main/res/layout/item.xml
  08 implementation/Mobile App/app/src/main/res/values/strings.xml
Labels: feature
