Repository VirtualZeth/new-yorker.dk, pull requests merged in 2021-05, with the labels that each got.

#6 Tilføj Use Case Diagram
  documents/UCD_Desktop.jpg
  documents/UCD_Desktop.xml
  documents/UCD_Mobil.jpg
  documents/UCD_Mobil.xml
  documents/Visionsdokument.md
Labels: documentation

#31 Mockup
  documents/mockup/Kontakt os - modal.png
  documents/mockup/Kontakt os.png
  documents/mockup/forside.png
  documents/mockup/oversigt.png
  documents/mockup/redigering.png
Labels: design

#34 Update Mockup
  documents/mockup/Kontakt os - modal.png
  documents/mockup/Kontakt os.png
  documents/mockup/forside.png
  documents/mockup/oversigt.png
  documents/mockup/redigering.png
Labels: design

#40 Create Teknologi-IOS.md
  09 Report/Danijel/Teknologi-IOS.md
Labels: report

#38 Vision
  01 Business Modeling/Visionsdokument.md
Labels: documentation

#47 Lower minimum SDK
  08 implementation/Mobile App/.gitignore
  08 implementation/Mobile App/.idea/.gitignore
  08 implementation/Mobile App/.idea/gradle.xml
  08 implementation/Mobile App/.idea/misc.xml
  08 implementation/Mobile App/.idea/sonarlint/issuestore/index.pb
  08 implementation/Mobile App/.idea/vcs.xml
  08 implementation/Mobile App/app/build.gradle
  08 implementation/Mobile App/app/src/androidTest/java/com/example/newyorkerdk/ExampleInstrumentedTest.java
  08 implementation/Mobile App/app/src/main/AndroidManifest.xml
  08 implementation/Mobile App/app/src/main/java/com/example/newyorkerdk/MainActivity.java
  08 implementation/Mobile App/app/src/main/res/values-night/themes.xml
  08 implementation/Mobile App/app/src/main/res/values/strings.xml
  08 implementation/Mobile App/app/src/main/res/values/themes.xml
  08 implementation/Mobile App/app/src/test/java/com/example/newyorkerdk/ExampleUnitTest.java
  08 implementation/Mobile App/gradle/wrapper/gradle-wrapper.properties
  08 implementation/Mobile App/gradlew
  08 implementation/Mobile App/gradlew.bat
Labels: bug

#42 Add ssd for tilføj vare
  .idea/modules.xml
  .idea/new-yorker.dk.iml
  .idea/runConfigurations.xml
  .idea/shelf/Uncommitted_changes_before_Update_at_25_05_2021_10_56_[Default_Changelist]/SSD_Tilføj_Vare.png
  .idea/shelf/Uncommitted_changes_before_Update_at_25_05_2021_10_56_[Default_Changelist]/SSD_Tilføj_Vare.vsdx
  .idea/shelf/Uncommitted_changes_before_Update_at_25_05_2021_10_56_[Default_Changelist]/shelved.patch
  .idea/shelf/Uncommitted_changes_before_Update_at_25_05_2021_10_56__Default_Changelist_.xml
  .idea/sonarlint/issuestore/index.pb
  .idea/vcs.xml
  .idea/workspace.xml
Labels: documentation

#54 Create UC_Redigere_Vare.md
  02 Requirements/useCases/UC_Redigere_Vare.md
Labels: documentation
